name: 'emulator.wtf'
author: 'emulator.wtf'
description: 'A collection of actions to test your project with emulator.wtf.'
branding:
  color: orange
  icon: smartphone
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo "::error::Use 'emulator-wtf/actions/run-tests@v1.0.0' to run your tests, \
          'emulator-wtf/actions/use-emulator@v1.0.0' to obtain an emulator or \
          'emulator-wtf/actions/configure-credentials@v1.0.0' to use an OIDC token"
        exit 1
