name: Test invoke-session
permissions:
  contents: read
  id-token: write
on:
  pull_request:
    paths:
    # action metadata changes
    - invoke-session/**
    # sources & direct dependencies
    - src/invoke-session/**
    - src/lib/**
    # npm/ts config
    - '*.json'
    # workflow file itself
    - .github/workflows/test_invoke_session.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
    - uses: jdx/mise-action@v3
      with:
        install: false
    - name: Rebuild
      run: mise dist
    - uses: ./configure-credentials
      with:
        oidc-configuration-id: ${{ vars.EW_OIDC_ID }}
    - name: Setup ew-cli
      uses: ./setup-ew-cli
    - name: Run emulator session
      id: ew-cli
      uses: ./invoke-session
      with:
        devices: model=Pixel2,version=33,gpu=auto
    - name: Print adb ports
      run: |
        echo "Attached ${{ steps.ew-cli.outputs.adb_attached }}"
        echo "Attached json ${{ steps.ew-cli.outputs.adb_attached_json }}"
        echo "Forwarded ${{ steps.ew-cli.outputs.adb_port_forwarded }}"
        echo "Forwarded json ${{ steps.ew-cli.outputs.adb_port_forwarded_json }}"
    - name: Validate adb connection
      run: |
        $ANDROID_HOME/platform-tools/adb shell whoami
