name: Test invoke-session
permissions:
  contents: read
  id-token: write
on:
  pull_request:
    paths:
    # action metadata changes
    - invoke-session/**
    # sources & direct dependencies
    - src/invoke-session/**
    - src/lib/**
    # npm/ts config
    - '*.json'
    # workflow file itself
    - .github/workflows/test_invoke_session.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v6.3.0 # zizmor: ignore[unpinned-uses] immutable tag
      with:
        node-version: '24'
    - uses: jdx/mise-action@v4.0.1 # zizmor: ignore[unpinned-uses] immutable tag
      with:
        install: false
    - name: Rebuild
      run: mise dist
    - uses: ./configure-credentials
      with:
        oidc-configuration-id: ${{ vars.EW_OIDC_ID }}
    - name: Setup ew-cli
      uses: ./setup-ew-cli
    - name: Run emulator session
      id: ew-cli
      uses: ./invoke-session
      with:
        devices: model=Pixel2,version=33,gpu=auto
    - name: Print adb ports
      env:
        ADB_ATTACHED: ${{ steps.ew-cli.outputs.adb_attached }}
        ADB_ATTACHED_JSON: ${{ steps.ew-cli.outputs.adb_attached_json }}
        ADB_PORT_FORWARDED: ${{ steps.ew-cli.outputs.adb_port_forwarded }}
        ADB_PORT_FORWARDED_JSON: ${{ steps.ew-cli.outputs.adb_port_forwarded_json }}
      run: |
        echo "Attached ${ADB_ATTACHED}"
        echo "Attached json ${ADB_ATTACHED_JSON}"
        echo "Forwarded ${ADB_PORT_FORWARDED}"
        echo "Forwarded json ${ADB_PORT_FORWARDED_JSON}"
    - name: Validate adb connection
      run: |
        $ANDROID_HOME/platform-tools/adb shell whoami
