name: Test use-emulator
permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write
on:
  pull_request:
    paths:
    - src/**
    - node_modules/**
    - '*.json'
    - use-emulator/**
    - .github/workflows/test_use_emulator.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: emulator-wtf/configure-credentials@v1
      with:
        oidc-configuration-id: ${{ vars.EW_OIDC_ID }}
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
    - uses: jdx/mise-action@v3
      with:
        install: false
    - run: mise dist
    - uses: ./use-emulator
      id: ew-cli
    - name: Print adb ports
      run: |
        echo "Attached ${{ steps.ew-cli.outputs.adb_attached }}"
        echo "Attached json ${{ steps.ew-cli.outputs.adb_attached_json }}"
        echo "Forwarded ${{ steps.ew-cli.outputs.adb_port_forwarded }}"
        echo "Forwarded json ${{ steps.ew-cli.outputs.adb_port_forwarded_json }}"
    - name: Validate adb connection
      run: |
        $ANDROID_HOME/platform-tools/adb shell whoami
