name: Test run-tests
permissions:
  contents: read
  id-token: write
on:
  pull_request:
    paths:
    # action metadata changes
    - run-tests/**
    # sources & direct dependencies
    - src/run-tests/**
    - src/setup-ew-cli/**
    - src/invoke/**
    - src/lib/**
    # npm/ts config
    - '*.json'
    # workflow file itself
    - .github/workflows/test_run_tests.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v6.3.0 # zizmor: ignore[unpinned-uses] immutable tag
      with:
        node-version: '24'
    - uses: jdx/mise-action@v4.0.1 # zizmor: ignore[unpinned-uses] immutable tag
      with:
        install: false
    - run: mise dist
    - uses: ./configure-credentials
      with:
        oidc-configuration-id: ${{ vars.EW_OIDC_ID }}
    - run: curl -o minimal.apk -sS https://maven.emulator.wtf/releases/wtf/emulator/minimal/0.0.2/minimal-0.0.2.apk
    - run: curl -o minimal-test.apk -sS https://maven.emulator.wtf/releases/wtf/emulator/minimal/0.0.2/minimal-0.0.2-test.apk
    - uses: ./run-tests
      with:
        app: minimal.apk
        test: minimal-test.apk
