name: Test use-emulator
permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write
on:
  pull_request:
    paths:
      - .github/actions/invoke-session/**
      - .github/workflows/test_invoke_session.yml
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    # PREP
    - uses: actions/checkout@v5
    - uses: emulator-wtf/configure-credentials@v1
      with:
        oidc-configuration-id: ${{ vars.EW_OIDC_ID_PRIVATE }}
    - name: Setup ew-cli
      uses: emulator-wtf/setup-ew-cli@v0.9.11
      with:
        version: 1.0.1
    - name: Run emulator session
      id: ew-cli
      uses: ./.github/actions/invoke-session
      with:
        devices: model=Pixel2,version=33,gpu=auto
    - name: Print adb ports
      run: |
        echo "Attached ${{ steps.ew-cli.outputs.adb_attached }}"
        echo "Attached json ${{ steps.ew-cli.outputs.adb_attached_json }}"
        echo "Forwarded ${{ steps.ew-cli.outputs.adb_port_forwarded }}"
        echo "Forwarded json ${{ steps.ew-cli.outputs.adb_port_forwarded_json }}"
    - name: Validate adb connection
      run: |
        $ANDROID_HOME/platform-tools/adb shell whoami
