name: Test setup-ew-cli
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - uses: jdx/mise-action@v3
        with:
          install: false
      - run: mise dist
      - uses: ./setup-ew-cli
