name: Test configure-credentials
permissions:
  contents: read
  id-token: write
on:
  pull_request:
    paths:
    # action metadata changes
    - configure-credentials/**
    # sources & direct dependencies
    - src/configure-credentials/**
    - src/lib/**
    # npm/ts config
    - '*.json'
    # workflow file itself
    - .github/workflows/test_configure_credentials.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
    - uses: jdx/mise-action@v3
      with:
        install: false
    - run: mise dist
    - uses: ./configure-credentials
      with:
        oidc-configuration-id: '414eac8b-5d17-4860-915f-37329ceb1dff'
    - uses: ./setup-ew-cli
    - run: ew-cli --models
